source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target "CastExample" do
  pod 'GoogleAds-IMA-iOS-SDK', '~> 3.4'
  pod 'google-cast-sdk'
  pod 'google-cast-remote-display-sdk'
end

